name: tour_guide
description: Graduation Project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  url_launcher: ^6.1.0
  cupertino_icons: ^1.0.4
  animated_splash_screen: ^1.2.0
  cloud_firestore: ^3.1.10
  modal_progress_hud: ^0.1.3
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.9
  firebase_storage: ^10.2.9
  provider: ^6.0.2
#  location: ^4.3.0
  permission_handler: ^9.2.0
  geolocator: ^8.2.0
  flutter_spinkit: ^5.1.0
  geocoding: ^2.0.4
  geocode: 1.0.1
  google_maps_flutter: ^2.1.4
  country_state_city_picker: ^1.2.8
  fluttertoast: ^8.0.9
  google_map_polyline_new: ^0.3.0+2
  flutter_polyline_points: ^1.0.0
  translator: ^0.1.7
  clipboard: ^0.1.3
  http: ^0.13.4
  google_fonts: any



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

  flutter_native_splash: ^1.2.1

flutter_native_splash:
  color: "#f9f9f9"
  image: assets/splash.png
  android: true
  ios: true
  web: true

flutter_icons:
  android: true
  image_path: "images/tour.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_forgeround: "images/forgeround.png"

flutter:


  uses-material-design: true

  assets:
     - images/
     - assets/

